services:
  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    command: --server-id=1 --log-bin=mysql-bin --binlog-format=row
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_master_database 
      MYSQL_USER: replication_user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-master:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf:ro

  mysql-slave:
    image: mysql:8.0
    container_name: mysql-slave
    depends_on:
      - mysql-master
    command: --server-id=2 --log-bin=mysql-bin --binlog-format=row
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_master_database
      MYSQL_USER: replication_user
      MYSQL_PASSWORD: user_password
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-slave:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf:ro

  mysql-slave-2:
    image: mysql:8.0
    container_name: mysql-slaveII
    depends_on:
      - mysql-master
    command: --server-id=3 --log-bin=mysql-bin --binlog-format=row
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_master_database
      MYSQL_USER: replication_user
      MYSQL_PASSWORD: user_password
    ports:
      - "3308:3306"
    volumes:
      - ./mysql-slaveII:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf:ro
